services:
  - type: web
    name: meccha-chameleon-solo
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit
